export const LOAD_TRAININGS_AUTHOR = "LOAD_TRAININGS";
export const PAGINATE_TRAININGS_AUTHOR = "PAGINATE_TRAININGS";
export const UPDATE_SORT_AUTHOR = "UPDATE_SORT";
export const UPDATE_TRAININGS_AUTHOR = "UPDATE_TRAININGS_AUTHOR";
