export const LOAD_USER = "LOAD_USER";
export const LOAD_ACCOUNT_AND_USER = "LOAD_ACCOUNT_AND_USER";
export const GET_USER_SKILL_INTEREST = "GET_USER_SKILL_INTEREST";
export const PAGINATE_USER_SKILL_INTEREST = "PAGINATE_USER_SKILL_INTEREST";
export const GET_SKILLS = "GET_SKILLS";
export const PAGINATE_SKILLS = "PAGINATE_SKILLS";
export const DELETE_USER_SKILL_INTEREST = "DELETE_USER_SKILL_INTEREST";