export const LOAD_TRAININGS = "LOAD_TRAININGS";
export const UPDATE_LOTYPES_FILTERS = "UPDATE_LOTYPES_FILTERS";
export const UPDATE_LEARNERSTATE_FILTERS = "UPDATE_LEARNERSTATE_FILTERS";
export const UPDATE_SKILLNAME_FILTERS = "UPDATE_SKILLNAME_FILTERS";
export const UPDATE_LOFORMAT_FILTERS = "UPDATE_LOFORMAT_FILTERS";
export const UPDATE_TAGS_FILTERS = "UPDATE_TAGS_FILTERS";

export const PAGINATE_TRAININGS = "PAGINATE_TRAININGS";
